// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using MovieGram.Data;

namespace MovieGram.Migrations
{
    [DbContext(typeof(MovieContext))]
    partial class MovieContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.5")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("MovieGram.Models.Movie", b =>
                {
                    b.Property<int>("MovieId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Director")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Genre")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Language")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("ReleaseDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieId");

                    b.ToTable("Movies");

                    b.HasData(
                        new
                        {
                            MovieId = 1,
                            Description = "Events escalate from weird to terrifying as they contend with the house's batty owner, her imposing son, a moody Swedish lepidopterist, a pedantic English professor, an extraordinarily rare butterfly, the world's best blueberry muffins, a .44 Magnum, a demented serial killer, and one very strict rulebook.",
                            Director = "D.W.Young",
                            Genre = "Suspense",
                            Language = "English",
                            ReleaseDate = new DateTime(2021, 5, 8, 17, 10, 9, 425, DateTimeKind.Local).AddTicks(2015),
                            Title = "The Happy House"
                        },
                        new
                        {
                            MovieId = 2,
                            Description = "When corpses drained of blood begin to show up in a European village, vampirism is suspected to be responsible.",
                            Director = "Frank R. Strayer",
                            Genre = "Horror",
                            Language = "German",
                            ReleaseDate = new DateTime(2021, 5, 11, 17, 10, 9, 426, DateTimeKind.Local).AddTicks(6298),
                            Title = "The Vampire Bat"
                        },
                        new
                        {
                            MovieId = 3,
                            Description = "After several years playing NFL professional football, 25 year-old Kyle Bishop (Lance Gross) is released from his fourth team in three years. Kyle returns to his hometown, broke and at a complete loss about what he will do for a living. After an initially cold reception.",
                            Director = "Matthew A. Cherry",
                            Genre = "Romance",
                            Language = "English",
                            ReleaseDate = new DateTime(2021, 5, 14, 17, 10, 9, 426, DateTimeKind.Local).AddTicks(6402),
                            Title = "The Last Fall"
                        },
                        new
                        {
                            MovieId = 4,
                            Description = "A travelling troupe of jousters and performers are slowly cracking under the pressure of hick cops, financial troubles and their failure to live up to their own ideals. The group's leader, King Billy, is increasingly unable to maintain his warrior's rule while the Black Knight is being tempted away to LA and stardom.",
                            Director = "George A. Romero",
                            Genre = "Drama",
                            Language = "Swedish",
                            ReleaseDate = new DateTime(2021, 5, 17, 17, 10, 9, 426, DateTimeKind.Local).AddTicks(6408),
                            Title = "Knightriders"
                        });
                });

            modelBuilder.Entity("MovieGram.Models.MovieShowtimes", b =>
                {
                    b.Property<int>("MovieShowtimeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("MovieId")
                        .HasColumnType("int");

                    b.Property<string>("Time")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("MovieShowtimeId");

                    b.HasIndex("MovieId");

                    b.ToTable("MovieShowTimes");

                    b.HasData(
                        new
                        {
                            MovieShowtimeId = 1,
                            MovieId = 1,
                            Time = "10:00"
                        },
                        new
                        {
                            MovieShowtimeId = 2,
                            MovieId = 1,
                            Time = "12:00"
                        },
                        new
                        {
                            MovieShowtimeId = 3,
                            MovieId = 1,
                            Time = "14:00"
                        },
                        new
                        {
                            MovieShowtimeId = 4,
                            MovieId = 1,
                            Time = "16:00"
                        },
                        new
                        {
                            MovieShowtimeId = 5,
                            MovieId = 2,
                            Time = "11:00"
                        },
                        new
                        {
                            MovieShowtimeId = 6,
                            MovieId = 2,
                            Time = "12:00"
                        },
                        new
                        {
                            MovieShowtimeId = 7,
                            MovieId = 2,
                            Time = "14:00"
                        },
                        new
                        {
                            MovieShowtimeId = 8,
                            MovieId = 2,
                            Time = "17:00"
                        },
                        new
                        {
                            MovieShowtimeId = 9,
                            MovieId = 3,
                            Time = "16:00"
                        },
                        new
                        {
                            MovieShowtimeId = 10,
                            MovieId = 3,
                            Time = "17:00"
                        },
                        new
                        {
                            MovieShowtimeId = 11,
                            MovieId = 3,
                            Time = "18:00"
                        },
                        new
                        {
                            MovieShowtimeId = 12,
                            MovieId = 3,
                            Time = "19:00"
                        },
                        new
                        {
                            MovieShowtimeId = 13,
                            MovieId = 4,
                            Time = "10:00"
                        },
                        new
                        {
                            MovieShowtimeId = 14,
                            MovieId = 4,
                            Time = "13:00"
                        },
                        new
                        {
                            MovieShowtimeId = 15,
                            MovieId = 4,
                            Time = "15:00"
                        },
                        new
                        {
                            MovieShowtimeId = 16,
                            MovieId = 4,
                            Time = "18:00"
                        });
                });

            modelBuilder.Entity("MovieGram.Models.MovieShowtimes", b =>
                {
                    b.HasOne("MovieGram.Models.Movie", null)
                        .WithMany("MovieShowtimes")
                        .HasForeignKey("MovieId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("MovieGram.Models.Movie", b =>
                {
                    b.Navigation("MovieShowtimes");
                });
#pragma warning restore 612, 618
        }
    }
}
